---
title: "Command-line use of bioinformatics tools"
author: "Jacques van Helden"
date: 'Created: 8/10/2018; last update: `r Sys.Date()`'
output:
  html_document:
    self_contained: false
    fig_caption: yes
    highlight: zenburn
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
  md_document:
    variant: markdown_github
  pdf_document:
    fig_caption: yes
    highlight: zenburn
    toc: yes
    toc_depth: 2
  word_document:
    toc: yes
    toc_depth: 2
#bibliography: ./geneset_functional_analysis.bib
---


```{r setup, include=FALSE}
library(knitr, warn.conflicts = FALSE)
knitr::opts_chunk$set(
  echo = TRUE, 
  results = TRUE, 
  message = FALSE,
  fig.align = "center")

dir.main <- "~/IFB/NNCR/using_IFB_NNCR/"
dir.tp <- file.path(dir.main, "practicals", "")
setwd(dir.tp)

```

****************************************************************
# Course home page

This practical is part of a series of tutorials ***Using the resources of the IFB National Network of Ccomputing Resources** (**NNCR**)*, available at **<https://jvanheld.github.io/using_IFB_NNCR/>**


****************************************************************
# Instructions  pour les étudiants AMU

- Le TP qui suit est rédigé en anglais, pour vous familiariser avec la langue utilisée sur l'ensemble des ressources bioinformatiques internationales. 

- Ce tutoriel repose sur l'utilsation du réseau national de ressources informatiques (**National Network of Computing Resources**, **NNCR**) de l'**Institut Français de Bioinformatique** (**IFB**). 

- Pour ces premiers travaux pratiques, nous utiliserons le serveur prototype du NNCR (***Proof of concept***, ***POC***), qui est actuellement en phase de test. Vous avez l'honneur d'être les premiers utilisateurs de ces machines. Si vous rencontrez des difficultés, n'hésitez donc pas à me les signaler. 

- En début de TP je communiqueral à chaque étudiant un login qui lui permettra d'accéder à ces ressources jusqu'à la fin de la session de janvier. 


****************************************************************
# Resources

|  Name | URL  |
|----------------|-------------------------------------------------------|
| IFB |  <http://france-bioinformatique.fr/> <br>Site Web de l'Institut Français de bioinformatique |
| Doc NNCR | <http://taskforce-nncr.gitlab.poc-nncr-ifb.fr/doc/> |
| NNCR POC | hpc.poc-nncr-ifb.fr<br>Cluster "Proof of concept" (POC) du NNCR, accessible par ssh (requiert un login personnel) |

<!--| Anaconda | <https://anaconda.org/> |-->

****************************************************************
# Goal of this practical

The goal of this practical is to learn using bioinformatics tools on the Unix command line. 

****************************************************************
# Introduction

****************************************************************
# Tutorial


## Opening a connection to the IFB cluster

In a Unix terminal, open an ssh connection to the IFB cluster.

```{bash eval=FALSE}
ssh yourlogin@hpc.poc-nncr-ifb.fr
```

At your first login, we recommend you to change your password, for the sake of security. This also lets you choose a password that you can remember. 

```{bash eval=FALSE}
passwd
```


Check the host name

```{bash eval=FALSE}
hostname
```

This should display the following result:


```
slurm-client.ifb.local
```

***Attention!*** You are now connected to the login machine of the cluster, whose only function is to give you access to the computing nodes. <font color="red">**This machine  should never be used to perform computation**</font>. Indeed, running tasks on this machine would be very inefficient for you (there is a single CPU) and perturbate the connections of other users. 



## Checking your environment

```{bash eval=FALSE}
## Get your login
whoami

## Print the path to your home directory
echo $HOME

### What is your shell ?
echo $SHELL

## Get your path
echo $PATH

## Print all your environment variables
printenv
```


## Running an interactive session on a cluster node

Normally, tasks should be sent to the cluster via de job scheduler. 

However, for this introductory tutorial we will start tasks on a node of the cluster. 

For this, we will use the command `sinteractive` command, which opens a bash session on one of the nodes of the cluster. You can then check the name of the node on which your interactive session has been open. 

```{bash eval=FALSE}
sinteractive

## Check the host name (it should be different from the login machine)
hostname
```

**Notes: ** 

1. <font color="red">The interactive mode is not the normal way to use cluster</font>. It is convenient for didactic purposes (a tutorial like this one) to run a quick test or, in some cases, to debug a script. We will show in a separate section the proper way to submit taks to the job scheduler (`slurm`). 

2. The command `sinteractive` does several things to ease your work. It opens an interactive session to the cluster, and starts an application named `screen`, which keeps the session open even if you are disconnected for some reason (network interruption, time to quit your office and go back home). You can then restart the session later and find it exactly in the state you left it before loosing the connection.

3. For more information read the doc at <http://taskforce-nncr.gitlab.poc-nncr-ifb.fr/doc/sinteractive.html>

You are now ready to start using the NNCR facilities. 



****************************************************************

# Supplementary information

- [Documentation du NNCR](http://taskforce-nncr.gitlab.poc-nncr-ifb.fr/doc/)


<!--
- [Sessions interactives avec slurm](https://it.igbmc.fr/doku.php?id=en:documentation:calcul-scientifique:sinteractive)
-->

****************************************************************
# References







